enable-module-update = true
#patches-version = "latest"
patches-version = "dev"
cli-version = "dev"

[YouTube-Extended]
Enable=true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "module"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
