enable-module-update = true
parallel-jobs = 1
patches-version = "latest"
#patches-version = "dev"
cli-version = "latest"

[YouTube-Extended]
Enable=true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "module"
version = "auto"
#version = "19.16.39"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom branding name for YouTube' 'Swipe controls'"
patcher-args = "-e 'Theme' -OlightThemeBackgroundColor=@android:color/white -OdarkThemeBackgroundColor=@android:color/black"

